### ISSUE TITLE
How to define a recursive rule with Python style?

### ISSUE THREAD

**Issue by berzi** [textX/Arpeggio#90]
Hi, I have the following grammar at the moment:
```python
# RegExMatch as Regex


def number():
    return Regex("[0-9]")


def quantifier():
    return "{", number, Optional(",", number), "}"


def char():
    return Regex(r"[a-zA-Z-']")


def literal():
    return [char, (char, quantifier)]


def character_class():
    return "[", OneOrMore(char), "]", Optional(quantifier)


def capture_group():
    # [1]
    return "(", OneOrMore([literal, character_class]), ")", Optional(quantifier)


def expression():
    return [literal, capture_group, character_class]


def genex():
    return OneOrMore(expression), EOF
```

I would like to add `expression` to the `capture_group` rule, inside `OneOrMore` on the line marked by my comment.

Obviously I can't just reference `expression` the way I do elsewhere, because it's define below and can't be moved above. Is there some special syntax that allows me to do what I need here, or is it not possible?

I believe this would not be an example of left recursion since the rule starts with an unambiguous literal `(`, but I'm frankly a bit of a noob when it comes to parsing so I might be wrong. Suggestions?

**Comment by igordejanovic** [comment]
> Obviously I can't just reference `expression` the way I do elsewhere, because it's define below and can't be moved above. Is there some special syntax that allows me to do what I need here, or is it not possible?
> 

There should be no problem in forward referencing of `expression` as a function body is evaluated when a function is called, not when it is defined/created, so by the time it is evaluated all functions are defined. What error have you got?

> I believe this would not be an example of left recursion since the rule starts with an unambiguous literal `(`, but I'm frankly a bit of a noob when it comes to parsing so I might be wrong. Suggestions?

I think you are right. There should be no left recursion as far as I can tell. Haven't tried it though.

BTW, your `literal` rule seems wrong as you are using ordered choice where the second alternative `(char, quantifier)` can never match as the first alternative `char` will always succeed before the second (it is the prefix of the second). You should reorder alternatives to have longer matching alternatives tried first. You can always run the parser in debug mode to see where the problem is.

**Comment by berzi** [comment]
My editor was detecting it as an undefined reference, but now it seems to be resolved, it was a false alarm after all.

Thank you for catching that about `literal` and thank you for the reply. So far, Arpeggio is proving very fun to use.
